spotlight/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Admin Panel
    path('admin/', admin.site.urls),
    # Home App
    path('', include('home_app.urls')),
    # Desk App
    path('', include('desk_app.urls')),
    # Profile App
    path('', include('profile_app.urls')),
    # Core Auth System
    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

spotlight/profile_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    # Contributions
    path('contributions/', views.contributions, name='contributions'),
    # Desk Management
    path('management/', views.desk_management, name='desk_management'),
    # Settings
    path('<str:officename>/profile/settings/', views.settings, name='settings'),
]

spotlight/desk_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from profile_app.models import ProfileSettings
from home_app.models import Office


# DESK'S
class Desk(models.Model):
    office = models.ForeignKey(Office, on_delete=models.CASCADE)
    sub_editor = models.ForeignKey(User, on_delete=models.CASCADE)
    office = models.ForeignKey(
        Office, on_delete=models.CASCADE, null=True, blank=True
    )
    image = models.ImageField(
        upload_to='deks_images/', blank=False, null=False
    )
    CATEGORY_CHOICES = (
        ('WORLD', 'fa fa-globe'),
        ('METRO', 'fa fa-building'),
        ('POLITICS', 'fa-flag'),
        ('BUSINESS', 'fa fa-suitcase'),
        ('TECH', 'fa fa-code'),
        ('SCIENCE', 'fa fa-flask'),
        ('OPINION', 'fa fa-gavel'),
        ('HEALTH', 'fa fa-heart'),
        ('SPORTS', 'fa fa-bicycle'),
        ('ARTS', 'fa fa-paint-brush'),
        ('BOOKS', 'fa fa-book'),
        ('STYLE', 'fa fa-eye'),
        ('TRAVEL', 'fa fa-plane'),
        ('MAGAZINE', 'fa fa-file'),
        ('TABLOID', 'fa fa-phone'),
    )
    CATEGORY_COLOR_CHOICES = (
        ('WORLD', '#3498DB'),
        ('METRO', '#2980B9'),
        ('POLITICS', '#5D6D7E'),
        ('BUSINESS', '#2E4053'),
        ('TECH', '#F4D03F'),
        ('SCIENCE', '#2ECC71'),
        ('OPINION', '#9B59B6'),
        ('HEALTH', '#E74C3C'),
        ('SPORTS', '#58D68D'),
        ('ARTS', '#F39C12'),
        ('BOOKS', '#E67E22'),
        ('STYLE', '#F5B7B1'),
        ('TRAVEL', '#BB8FCE'),
        ('MAGAZINE', '#8E44AD'),
        ('TABLOID', '#A569BD'),
    )
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    category_color = models.CharField(
        max_length=50, choices=CATEGORY_COLOR_CHOICES
    )
    name = models.CharField(max_length=30)
    description = models.TextField()
    creation_date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.name


# DESK WORKERS
class DeskWorkers(models.Model):
    worker = models.ForeignKey(User, on_delete=models.CASCADE)
    joined_desk = models.ForeignKey(Desk, on_delete=models.CASCADE)

    def __str__(self):
        return self.worker.username


# DESK TO-DO
class DeskToDo(models.Model):
    desk = models.ForeignKey(Desk, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    publish_date = models.DateField(default=timezone.now)
    task_completed = models.BooleanField(default=False)

    def __str__(self):
        return self.desk.name


# DESK ARTICLE
class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    author_settings = models.ForeignKey(
            ProfileSettings, on_delete=models.CASCADE, null=True
        )
    desk = models.ForeignKey('Desk', on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=120)
    content = models.TextField()
    publish_date = models.DateField(default=timezone.now)
    category = models.CharField(max_length=50)
    pushed_to_done = models.BooleanField(default=False)
    pushed_to_publish = models.BooleanField(default=False)

    def __str__(self):
        return self.author.username + ' | ' + self.title[:50] + "..."


# ARTICLE COMMENTS
class ArticleComment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    content = models.TextField()
    publish_date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.article.title

spotlight/profile_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# USER SETTINGS
class ProfileSettings(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_photo = models.ImageField(
        upload_to='profile_photos/', blank=True, null=True
    )
    bio = models.TextField(blank=False, null=False)
    personal_link = models.CharField(max_length=200, blank=False, null=False)

    def __str__(self):
        return self.user.username

spotlight/profile_app/forms.py
from django import forms
from django.forms import ModelForm
from profile_app.models import ProfileSettings


# SETTINGS FROM
class ProfileSettingsForm(ModelForm):
    class Meta:
        model = ProfileSettings
        fields = ['profile_photo', 'bio', 'personal_link']
        widgets = {
            "bio": forms.TextInput(
                attrs={'placeholder': 'Bio ...', 'class': 'settings_input',
                       'id': 'bio', }
            ),
            "personal_link": forms.TextInput(
                attrs={'placeholder': 'Personal URL', 'id': 'personal_link',
                       'class': 'settings_input', }
            ),
        }

spotlight/profile_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from profile_app.models import ProfileSettings
from desk_app.models import Desk, DeskWorkers, Article
from home_app.models import Office, OfficeWorkers
from profile_app.forms import ProfileSettingsForm


# CONTRIBUTIONS
# ------------------
# Desc: This is the overall summary page of the each user containing contribu-
#       -tions and and publised articles and so on.
@login_required
def contributions(request, officename):
    current_user = get_object_or_404(User, pk=request.user.id)

    # Article objects
    try:
        current_user_articles = Article.objects.filter(author=current_user)\
            .order_by('-publish_date')
    except ObjectDoesNotExist:
        current_user_articles = None

    # Settings Objects
    try:
        current_user_settings = ProfileSettings.objects.get(user=current_user)
    except ObjectDoesNotExist:
        current_user_settings = None

    # Desk objects
    try:
        current_user_desks = DeskWorkers.objects.filter(worker=current_user)
    except ObjectDoesNotExist:
        current_user_desks = None

    data = {
        'current_user': current_user,
        'has_profile_navbar': True,
        'current_user_settings': current_user_settings,
        'current_user_desks': current_user_desks,
        'current_user_articles': current_user_articles,
    }
    return render(request, 'profile_app/contributions.html', context=data)


# DESK MANAGEMENT
# ------------------
# Desc: This is where the user can manage its deks weather it want delete the
#       desk that it has joined earlier
@login_required
def desk_management(request):
    current_user = get_object_or_404(User, pk=request.user.id)

    # Settings Objects
    try:
        current_user_settings = ProfileSettings.objects.get(user=current_user)
    except ObjectDoesNotExist:
        current_user_settings = None

    # Desk objects
    try:
        current_user_desks = DeskWorkers.objects.filter(worker=current_user)
    except ObjectDoesNotExist:
        current_user_desks = None

    # Desk quit mechanism
    if request.POST.get("delete_desk_submit_btn"):
        hidden_id = request.POST.get("hidden_desk_id")
        desk = DeskWorkers.objects.get(pk=hidden_id)
        desk.delete()

    data = {
        'current_user': current_user,
        'has_profile_navbar': True,
        'current_user_settings': current_user_settings,
        'current_user_desks': current_user_desks,
    }
    return render(request, 'profile_app/desk_management.html', context=data)


# SETTINGS
# ------------------
# Desc: This is the section in your profile that contains the settings form th-
#       -at is used to change your profiles settings
@login_required
def settings(request, officename):
    current_user = get_object_or_404(User, pk=request.user.id)
    current_office = Office.objects.get(name=officename)
    try:
        office_worker = OfficeWorkers.objects.get(user=current_user)
    except ObjectDoesNotExist:
        office_worker = None

    # Settings Objects
    try:
        current_user_settings = ProfileSettings.objects.get(user=current_user)
    except ObjectDoesNotExist:
        current_user_settings = None

    # Desk objects
    try:
        current_user_desks = DeskWorkers.objects.filter(worker=current_user)
    except ObjectDoesNotExist:
        current_user_desks = None

    # Settings Mechanism
    if request.method == 'POST':
        settings_form = ProfileSettingsForm(request.POST, request.FILES)
        if settings_form.is_valid():
            profile_photo = settings_form.cleaned_data['profile_photo']
            bio = settings_form.cleaned_data['bio']
            personal_link = settings_form.cleaned_data['personal_link']
            try:
                # Update settings if there is a settings already
                update_settings = ProfileSettings.objects.get(
                    user=current_user
                )
                update_settings.profile_photo = profile_photo
                update_settings.bio = bio
                update_settings.personal_link = personal_link
                update_settings.save()
            except ObjectDoesNotExist:
                new_settings = ProfileSettings(
                    user=current_user, bio=bio, profile_photo=profile_photo,
                    personal_link=personal_link,
                )
                new_settings.save()
            return HttpResponseRedirect(
                '/' + str(current_office.name) + '/home/dashboard/'
            )
        else:
            print('form is not valid')
    else:
        settings_form = ProfileSettingsForm()

    data = {
        'current_user': current_user,
        'current_office': current_office,
        'office_worker': office_worker,
        'has_profile_navbar': True,
        'current_user_settings': current_user_settings,
        'current_user_desks': current_user_desks,
        'settings_form': settings_form,
    }
    return render(request, 'profile_app/settings.html', context=data)

spotlight/templates/profile_app/contributions.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css_link %}
<link rel="stylesheet" href="{% static 'profile_app/css/contributions_style.css' %}" />
{% endblock %}

{% block content %}
<div id="wrapper">
  <h3 id="header">Contributions</h3>
  <br />

  <hr />
  <img src="{{current_user_settings.profile_photo.url}}" alt="pp_image" height="60px" width="60px" />
  <h3>{{ current_user_settings.name }}</h3>
  <p>{{ current_user_settings.bio }}</p>
  <a href="{{ current_user_settings.personal_link }}"><i class="fa fa-link"></i> {{ current_user_settings.personal_link }}</a>

  <hr />
  <h4>Articles:</h4>
  <div id="articles-container">
    {% for article in current_user_articles %}
      <!-- cell -->
      <div id="article-cell">
        <h3>{{ article.title }}</h3>
        <h4 style="color:{{article.desk.get_category_color_display}}; border: 1px solid {{article.desk.get_category_color_display}}; display:inline-block; padding:3px; border-radius: 3px;">{{ article.category|lower }}</h4>
        <h5 style="margin-bottom:20px;">{{ article.publish_date }}</h5>
        <p>{{ article.content }}</p>
      </div><!-- article /cell -->
    {% endfor %}
  </div><!-- articles container -->

</div><!-- wrapper -->
{% endblock %}

spotlight/templates/profile_app/desk_management.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css_link %}
<link rel="stylesheet" href="{% static 'profile_app/css/desk_management.css' %}" />
{% endblock %}

{% block content %}
<div id="wrapper">
  <h3 id="header">Desk Management</h3>
  <br />

  <div id="desk-list-container">
    {% for desk in current_user_desks %}
      <!-- cell -->
      <div id="desk-cell">
        <h4><i class="{{ desk.joined_desk.get_category_display }}"></i> {{ desk.joined_desk.name }} </h4>
        <form id="delete_form" method="post" action="{% url 'desk_management' %}" id="delete_form">
          {% csrf_token %}
          <input type="hidden" name="hidden_desk_id" value="{{ desk.id }}" />
          <input type="submit" name="delete_desk_submit_btn" value="Quit" id="delete_desk_submit_btn">
        </form>
      </div><!-- /cell -->
    {% endfor %}
  </div>

</div><!-- wrapper -->
{% endblock %}

spotlight/templates/profile_app/settings.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css_link %}
<link rel="stylesheet" href="{% static 'profile_app/css/settings_style.css' %}" />
{% endblock %}

{% block content %}
<div id="wrapper">
  <h3 id="header">Settings</h3>
  <br />
  <form action="{% url 'settings' current_office.name %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label>Profile Photo</label>
    {{ settings_form.profile_photo }}
    <label style="margin-top:10px;">Biography</label>
    {{ settings_form.bio }}
    <label>Personal Link</label>
    {{ settings_form.personal_link }}
    <input type="submit" value="Update" name="settings_submit_button" id="update_button" width="55px"/>
  </form>
</div>
{% endblock %}